WindowManager:
    MainWindow:
    MondayWindow:
    TuesdayWindow:


<MainWindow>:
    name: "main_window"
    FloatLayout:
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: "wallper4.png"
        Button:
            size_hint: .35, .45
            pos_hint: {"x": .1, "y": .6}
            background_color: 0, 0, 0, 0

            on_press: root.sleep_on()
            on_release: root.sleep_off()
            Image:
                id: sleep_image
                source: "sleep.png"
                center_x: self.parent.center_x
                center_y: self.parent.center_y
        Button:
            size_hint: .35, .45
            pos_hint: {"x": .4, "y": .4}
            background_color: 0, 0, 0, 0

            on_press: root.tasks_on()
            on_release:
                root.tasks_off()
                app.root.current = "monday_window"
                root.manager.transition.direction = "up"
            Image:
                id: tasks_image
                source: "tasks.png"
                center_x: self.parent.center_x
                center_y: self.parent.center_y
        Button:
            size_hint: .35, .45
            pos_hint: {"x": .1, "y": .1}
            background_color: 0, 0, 0, 0

            on_press: root.goal_on()
            on_release: root.goal_off()
            Image:
                id: goal_image
                source: "goal.png"
                center_x: self.parent.center_x
                center_y: self.parent.center_y
<MondayWindow>:
    name: "monday_window"
    FloatLayout:
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: "wallper2.png"
        Button:
            size_hint: .1, .1
            pos_hint: {"x": .001, "y": .9}
            background_color: 0, 0, 0, 0

            on_release:
                app.root.current = "tuesday_window"
                root.manager.transition.direction = "right"
            Image:
                id: monday_left_image
                source: "left.png"
                center_x: self.parent.center_x
                center_y: self.parent.center_y
        Button:
            size_hint: .1, .1
            pos_hint: {"x": .9, "y": .9}
            background_color: 0, 0, 0, 0

            on_release:
                app.root.current = "tuesday_window"
                root.manager.transition.direction = "left"
            Image:
                id: monday_right_image
                source: "right.png"
                center_x: self.parent.center_x
                center_y: self.parent.center_y
        Button:
            text: "Home"
            size_hint: .1, .1

            on_release:
                app.root.current = "main_window"
                root.manager.transition.direction = "down"
        Button:
            size_hint: .1, .1
            pos_hint: {"x": .9, "y": .001}
            background_color: 0, 0, 0, 0
            Image:
                id: monday_plus_image
                source: "plus.png"
                center_x: self.parent.center_x
                center_y: self.parent.center_y
<TuesdayWindow>:
    name: "tuesday_window"
    FloatLayout:
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: "wallper2.png"
        Button:
            size_hint: .1, .1
            pos_hint: {"x": .001, "y": .9}
            background_color: 0, 0, 0, 0

            on_release:
                app.root.current = "monday_window"
                root.manager.transition.direction = "right"

            Image:
                id: tuesday_left_image
                source: "left.png"
                center_x: self.parent.center_x
                center_y: self.parent.center_y
        Button:
            size_hint: .1, .1
            pos_hint: {"x": .9, "y": .9}
            background_color: 0, 0, 0, 0

            on_release:
                app.root.current = "monday_window"
                root.manager.transition.direction = "left"
            Image:
                id: tuesday_right_image
                source: "right.png"
                center_x: self.parent.center_x
                center_y: self.parent.center_y
        Button:
            text: "Home"
            size_hint: .1, .1

            on_release:
                app.root.current = "main_window"
                root.manager.transition.direction = "down"
        Button:
            size_hint: .1, .1
            pos_hint: {"x": .9, "y": .001}
            background_color: 0, 0, 0, 0
            Image:
                id: tuesday_plus_image
                source: "plus.png"
                center_x: self.parent.center_x
                center_y: self.parent.center_y



